# Generated by Django 3.2.16 on 2023-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='wh',
            field=models.CharField(choices=[('Mostorod', 'Mostorod'), ('Basatin', 'Basatin'), ('Haram', 'Haram'), ('Basous', 'Basous'), ('All', 'All')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
