# Generated by Django 3.2.16 on 2023-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230505_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_fleet',
            field=models.BooleanField(default=False),
        ),
    ]
