# Generated by Django 3.2.16 on 2023-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_newuser_is_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='warehouse',
            field=models.CharField(choices=[('Mostorod', 'Mostorod'), ('Basatin', 'Basatin'), ('Haram', 'Haram'), ('Basous', 'Basous'), ('All', 'All')], max_length=255, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('Mostorod', 'Mostorod'), ('Basatin', 'Basatin'), ('Haram', 'Haram'), ('Basous', 'Basous'), ('All', 'All')], max_length=255, null=True, verbose_name='warehouse'),
        ),
    ]
