# Generated by Django 3.2.16 on 2023-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230507_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.CharField(blank=True, choices=[('Car Issue', 'Car Issue'), ('Discount Issue', 'Discount Issue'), ('Delay OR Failed', 'Delay OR Failed'), ('Partial Deliverey', 'Partial Deliverey'), ('Arrive Orders', 'Arrive Orders')], default='None', max_length=255, null=True, verbose_name='Tag'),
        ),
    ]
