# Generated by Django 3.2.16 on 2023-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ticket_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='wh_editable',
            field=models.BooleanField(default=False),
        ),
    ]
