# Generated by Django 3.2.16 on 2023-06-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ticketlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('WAITING', 'WAITING'), ('CLOSED', 'CLOSED'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
