# Generated by Django 3.2.16 on 2023-06-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_company_tag_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
