# Generated by Django 3.2.16 on 2023-06-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tag_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagTeam',
        ),
    ]
