# Generated by Django 3.2.16 on 2023-07-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_tag_tagteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='main.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='main.warehouse', verbose_name='Warehouse'),
        ),
    ]
