# Generated by Django 3.2.16 on 2023-07-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230713_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='wh',
        ),
    ]
